export const WORDS_FR = [
  // A
  'ABIME','ABORD','AIMER','AIGLE','ALGUE','ARBRE','ARENE','ASTRE','AVION','AVARE',
  'ADIEU','ALBUM','ALLIE','AMOUR','ANCRE','ANGLE','APPEL','APRES','ARCHE','ARDON',
  'AROSE','ATOME','AUBE','AUSSI','AVIDE','AVOIR','AZONE','AZOTE','ARRET','AGILE',
  'ABCDE','ABCES','ACHAT','ACIDE','ACIER','ACTIF','ADAGE','ADDAX','ADENT','ADMIT',
  'ADORE','ADRET','ADULT','AFIN','AGAVE','AGILE','AGITE','AGNEAU','AIDER','AIEUL',
  'AIOLI','AIRED','AIRER','AJONC','ALBUM','ALENE','ALERTE','ALGUE','ALIBI','ALITE',
  'ALLEE','ALLER','ALOES','ALOIR','ALORS','ALTER','AMBRE','AMOUR','AMPLE','AMUSE',
  'AMANT','AMONT','AMPHI','ANCRE','ANTRE','APODE','AROME','ARRET','ARCHE',
  // B
  'BALLE','BAZAR','BLANC','BLOND','BRUME','BULLE','BICHE','BILAN','BOIRE','BOITE',
  'BOLDE','BOMBE','BONNE','BOTTE','BOUEE','BOULE','BOURG','BRAVO','BRAVE','BREVE',
  'BRIDE','BRINS','BRION','BROIE','BRULE','BRUNE','BUSTE','BUTER','BANDE','BANJO',
  'BARBE','BARON','BARRE','BASSIN','BATEAU','BETON','BEIGE','BELLE','BEIGE','BESOIN',
  'BIERE','BIJOU','BISON','BLASE','BLEME','BLESS','BLEUS','BLIND','BLUES','BOCAL',
  'BOMBE','BONZE','BORDE','BORNE','BOSSE','BOTOX','BOUCS','BOUTS','BOXEN','BOXEZ',
  // C
  'CALME','CARTE','CHOSE','CRANE','CRABE','CHAMP','CHIEN','COEUR','CLAIR','CLONE',
  'CONTE','CORPS','CORDE','CORNU','COTES','COUDE','COUPE','COURS','COURT','CRANE',
  'CRAVE','CREUX','CRISE','CRUES','CULTE','CURLE','CABLE','CACOU','CADET','CADRE',
  'CAFRE','CAHOT','CAIEU','CAOUT','CAPSE','CARAT','CARPE','CASER','CAUSE','CEDER',
  'CENSE','CHALE','CHAOS','CHAPE','CHAUD','CHAUX','CHENE','CHERI','CHIER','CHOIX',
  'CHOUF','CIGALE','CIMIER','CIRQUE','CLORE','CLOWN','COCON','CODEX','COEUR','COFFRE',
  'COLLE','COLOR','COLZA','COMTE','CONGE','COQUE','CORAL','CORNU','COTTE','COUAC',
  'COUDE','COULE','COUPS','COUSU','CRABE','CRACK','CRAMP','CREDO','CREVE','CRIME',
  // D
  'DANSE','DENSE','DESIR','DETTE','DOUCE','DROIT','DUVET','DEBUT','DEBIT','DECOR',
  'DEFIS','DELTA','DEPOT','DESIR','DETTE','DEUIL','DIGUE','DIODE','DIRLO','DIVIN',
  'DOCTE','DOGUE','DOLCE','DOMMAGE','DOPER','DOSER','DOUAR','DOUZE','DROIT','DRONE',
  'DRUZE','DUNES','DUPEX','DUVET','DAUBE','DEBAT','DECEN','DECOR','DEFET','DEFIT',
  'DEGAS','DEGRE','DEHORS','DELIC','DENIM','DENSE','DEPOT','DERBY','DESDE','DESIR',
  // E
  'ECOLE','ECLAT','ELEVE','ENFIN','ESSOR','ETANG','ETUDE','EVEIL','ENGIN','ENVOI',
  'EPAVE','EPAULE','EPICE','EPOUX','ECART','ECRIRE','EDITE','EFFET','EGOUT','EIDER',
  'ELIRE','EMOIS','EMULE','ENCRE','ENFUI','ENNUI','ENROB','ENTRE','ENVIE','ENVOL',
  'EPAIS','EPURE','EQUIN','ERGOT','ERREUR','ESSOR','ETALE','ETAPE','ETENDU','ETIER',
  'ETOLE','ETRE','EVADE','EVEIL','EXCES','EXODE','EXTASE','ECRIRE',
  // F
  'FABLE','FERME','FLEUR','FOLIE','FORCE','FRUIT','FOYER','FOSSE','FORGE','FORME',
  'FORTE','FOUET','FOULE','FAGOT','FANAL','FARCE','FARDE','FAUCON','FAUNE','FAUVE',
  'FELIN','FELON','FEMUR','FENIL','FERIE','FERME','FESSE','FICHE','FIGUE','FILET',
  'FILLE','FILOU','FINES','FLEUR','FLAIR','FLAMME','FLEGME','FLORE','FLUET','FLUTE',
  'FONDU','FONTE','FORUM','FOSSE','FRAIS','FRANC','FRISE','FROID','FRONT','FUGUE',
  'FUNIN','FURET','FUTUR','FAUSSE',
  // G
  'GARDE','GRAIN','GRACE','GESTE','GORGE','GREVE','GENRE','GRAND','GELIF','GENOU',
  'GERBE','GILET','GIVRE','GLACE','GLANE','GLEBE','GLOBE','GLOME','GLOSS','GOBER',
  'GORET','GOSSE','GOUET','GOUGE','GOURD','GOUTTE','GRACE','GRADE','GRAIN','GRIVE',
  'GROIN','GROLE','GROOM','GUERE','GUEUX','GUIDE','GUISE','GUSTO','GYRUS',
  // H
  'HIVER','HERBE','HONTE','HAVRE','HUILE','HUTTE','HALLE','HALTE','HARDI','HARPE',
  'HASARD','HASTE','HAUTE','HAYON','HELAS','HERON','HORDE','HOULE','HYENE','HYMNE',
  'HYPER','HERBE','HEROE','HEROS','HIRON','HONNI','HONTE','HORDU','HUARD',
  // I
  'IMAGE','IDEAL','IVOIRE','INTER','INEPT','INERT','INDUE','INFUS','INGRE','INULE',
  'IRONE','IRURE','ISARD','ISERE','IVOIR','IVRES',
  // J
  'JOUER','JOUET','JOYAU','JOUTE','JUPON','JACOT','LACIS','JABOT','JACOT','JALON',
  'JAMBE','JARRE','JASPE','JATTE','JAUNE','JEUDI','JEUNE','JOUAL','JOUER','JOULE',
  'JOURD','JUTEUX',
  // L
  'LAINE','LARME','LASER','LIVRE','LAMPE','LACET','MANTE','LUNDI','LAGON','LAITE',
  'LANCE','LANDE','LAPIN','LASER','LASSO','LAUDE','LAURE','LAVEE','LEGER','LEVRE',
  'LIANE','LICOL','LIEGE','LIMER','LINGE','LITRE','LIVRE','LOCAL','LODGE','LOESS',
  'LOGER','LOPIN','LOQUE','LOURD','LUEUR','LUIRE','LUTIN','LYCHE',
  // M
  'MANGE','MASSE','MECHE','MONDE','MELON','NAPPE','NEIGE','NOEUD','NUAGE','MARDI',
  'MAREE','MARIN','MAROC','MARQUE','MASSE','MATIN','MECHE','MELEE','MELON','MEMRE',
  'MERLE','METAL','METRE','MEUTE','MICRO','MIEUX','MIJON','MIJON','MIMIC','MINOT',
  'MINUT','MOIRE','MOITE','MOLTE','MONDE','MORNE','MORSE','MORUE','MOTIF','MOULE',
  'MOYEN','MUCUS','MULET','MULTI','MURAL','MUSEE','MUTIN',
  // N
  'NATTE','NICHE','NOBLE','NOCIF','NOMBR','NONCE','NORIA','NOTER','NOVAU','NOYER',
  'NUIRE','NUQUE','NYMPHE',
  // O
  'OCEAN','ONCLE','OFFRE','ORDRE','OPERA','ORAGE','ORDIE','ORFEU','ORGUE','ORPIN',
  'ORTIE','OSIER','OUATE','OULET','OUTIL','OZONE',
  // P
  'PIANO','PLUIE','PLACE','PERLE','PECHE','PLAGE','PATTE','SAPIN','PAILLE','PALME',
  'PANDA','PANNE','PAUME','PAUSE','PAYOT','PEINE','PELER','PENTE','PERDU','PERSE',
  'PETIT','PIEGE','PILAF','PILOT','PINCE','PIVOT','PIXEL','PIZZO','POCHE','POEME',
  'POETE','POIDS','POILU','POLKA','PONCE','PONTE','PORCE','PORTO','POSIT','POUCE',
  'POULE','POUPE','PRISE','PROBE','PRUDE','PRUNE','PUBIS','PUISE',
  // Q
  'QUEUE','QUETE','QUINE',
  // R
  'RICHE','ROUGE','REINE','RAVIN','SCENE','TEMPS','SANTE','SUCRE','TABLE','TAPIS',
  'RADIS','RAGOT','RAILS','RAISIN','RAMPE','RAPHE','RAPIN','RATON','RAVET','REBUT',
  'RECIT','RECRU','REFUS','REGAL','REGLE','REJET','RELIE','REMIX','REPAS','REPLI',
  'REPOS','REPUE','RESEAU','REVUE','RIDER','RIEUR','RIGOT','RIVET','ROBER','ROBOT',
  'ROCHE','RODEO','ROSEE','ROTIN','ROTOR','ROUGE','ROULE','ROYAL','RUBAN','RUCHE',
  'RUGBY','RUINE','RURAL',
  // S
  'SABLE','SAUTE','SANTE','SAPIN','SUCRE','SOUPE','SAUCE','SAUGE','SAULE','SAUTE',
  'SAVON','SCION','SCOUT','SECHE','SEINE','SEIZE','SELLE','SEMER','SERAC','SERGE',
  'SERIE','SERIN','SERRE','SERUM','SIEGE','SIGNE','SILEN','SILEX','SINGE','SIROP',
  'SOBRE','SOCLE','SOEUR','SOLEX','SONDE','SONGE','SORTE','SOUCI','SOUPE','SOURD',
  'SOUS','SOYEZ','SQUAD','STAND','STELE','STEREO','STERE','STORE','STRIE','STUPA',
  'STYLO','SUAVE','SUBIR','SUEUR','SUITE','SUPER','SUPRA','SURGI','SURGI',
  // T
  'TABLE','TENIR','TERRE','TAPIS','TEMPS','TIGRE','TOXIC','TRACE','TRAIN','TRAIT',
  'TRAME','TRAPS','TREVE','TRIAL','TRIBU','TRIPE','TROLL','TRONE','TROPE','TROUP',
  'TROUX','TRUCK','TUILE','TUTIE','TYRAN','TABAC','TACON','TALON','TALUS','TAPAS',
  'TARDE','TARTE','TAUPE','TAXER','TEINT','TENON','TERCE','TERME','TIARE','TIBIA',
  'TIRET','TITRE','TOBOG','TOILE','TOISE','TOLET','TOLUE','TONDU','TONTE','TORDU',
  'TORIL','TORSE','TOXIN','TRAIL','TRAME','TRAPP','TREMA','TREVE',
  // U
  'UNITE','USINE','USAGE','ULCER','ULTRA','UNION','UTILE',
  // V
  'VALVE','VITRE','VACHE','VOILE','VERRE','VELAR','VELIN','VELOT','VENIN','VENIR',
  'VENTE','VERGE','VERTU','VESTE','VIDON','VIGNE','VIGOR','VILLA','VILLE','VIOLE',
  'VIPER','VIRES','VITAL','VITRE','VOGUE','VOLET','VOLTE','VOMIR','VOTER','VOUTE',
  // W X Y Z
  'WAGON','XENON','YACHT','ZESTE','ZONAL','ZEBRA',
]

export const WORDS_EN = [
  // A
  'APPLE','ADOBE','ABBOT','AFOOT','ALIBI','AXIOM','ABLED','ABODE','ABORT','ABOUT',
  'ABUZZ','ACORN','ACUTE','ADEPT','ADMIT','ADOPT','ADULT','AFTER','AGAPE','AGATE',
  'AGONY','AGREE','AHEAD','AIDED','AISLE','ALOFT','ALONE','ALONG','ALOOF','ALOUD',
  'ALURE','AMAZE','AMBER','AMBLE','AMEND','MIDST','AMONG','AMPLE','AMUSE','ANGEL',
  'ANGER','ANGLE','ANIME','ANNEX','ANTIC','ANVIL','APART','APHID','APPLY','APRON',
  'APTLY','ARBOR','ARDOR','ARGUE','ARISE','ARMOR','AROMA','AROSE','ARRAY','ATONE',
  'ATTIC','AUDIO','AUDIT','AUGUR','AUNTS','AVAIL','AVENGE','AVERT','AVOID','AWAIT',
  'AWAKE','AWARD','AWARE','AWFUL','AWOKE',
  // B
  'BRAVE','BIRCH','BOXER','BLAZE','BRINE','BATCH','BLUFF','BASIC','BASIL','BASIN',
  'BANJO','BADGE','BADLY','BAGEL','BAGGY','BAKED','BALMY','BANDY','BARGE','BARON',
  'BASAL','BASTE','BATCH','BATHE','BATTY','BEACH','BEADY','BEARD','BEAST','BEFIT',
  'BEGIN','BEING','BELOW','BENCH','BERRY','BEVEL','BEZEL','BIBLE','BIOME','BIRCH',
  'BISON','BITER','BLAND','BLANK','BLAST','BLEAT','BLEED','BLEND','BLESS','BLIMP',
  'BLIND','BLINK','BLOAT','BLOCK','BLOOD','BLOOM','BLOWN','BOARD','BOOBY','BOOST',
  'BOOTH','BOOTY','BORED','BOTCH','BRACE','BRAID','BRAKE','BRAND','BRASH','BRASS',
  'BRAWN','BREAD','BREAK','BREED','BREVE','BRIBE','BRIDE','BRILL','BRISK','BROIL',
  'BROOD','BROOK','BROTH','BROWN','BROWS','BRUNT','BRUSH','BRUTE','BUDGE','BUFFS',
  'BUILT','BULGE','BULKY','BUMPY','BUNNY','BURLY','BURNT','BURST','BUSHY','BYLAW',
  // C
  'CHAIR','CRANE','CRISP','CRAFT','CATCH','CRAWL','CANDY','CABIN','CADET','CAMEL',
  'CAMEO','CANAL','CARGO','CAROL','CARVE','CAUSE','CAULK','CAVES','CEDAR','CELLO',
  'CHALK','CHAMP','CHAOS','CHARM','CHASM','CHEAP','CHEAT','CHECK','CHEEK','CHEER',
  'CHESS','CHEST','CHIEF','CHILE','CHILL','CHINA','CHIVE','CHOIR','CHORD','CHORE',
  'CHOSE','CHURN','CIDER','CIVIL','CLAMP','CLANG','CLANK','CLASH','CLASP','CLASS',
  'CLEAN','CLEAR','CLEFT','CLERK','CLICK','CLIFF','CLING','CLOAK','CLOSE','CLOTH',
  'CLOUD','CLOUT','CLOWN','CLUCK','CLUED','CLUMP','CLUNG','COAST','COBRA','COMET',
  'COMIC','COMMA','COUCH','COULD','COUNT','COUPE','COVER','COVET','COZY','CRANE',
  'CRANK','CREAK','CREAM','CREEK','CREEP','CREST','CRIME','CRIMP','CRISP','CROAK',
  'CROSS','CROWD','CRUEL','CRUMB','CRUSE','CRUSH','CRUST','CRYPT','CUBIC','CURLY',
  'CURVE','CUTIE','CYBER','CYCLE','CYNIC',
  // D
  'DANCE','DEPOT','DERBY','DAISY','DEBUT','DADDY','DAILY','DALLY','DAMP','DANDY',
  'DARED','DEALT','DECAL','DECAY','DECOY','DECRY','DELTA','DENSE','DEPOT','DEPTH',
  'DIGIT','DINKY','DIRTY','DITTY','DIVER','DIZZY','DODGE','DOGMA','DOUBT','DOUGH',
  'DOUSE','DOWDY','DOWEL','DOZEN','DRAFT','DRAIN','DRAPE','DRAWL','DREAD','DREAM',
  'DRESS','DRIED','DRIFT','DRILL','DRINK','DROOP','DROVE','DROWN','DRUNK','DRYER',
  'DUCAT','DUSKY','DUSTY','DWARF','DWELL','DWELT',
  // E
  'EAGLE','ELBOW','EMBER','EQUIP','ELEGY','EARLY','EARTHY','EBONY','EERIE','EIGHT',
  'EJECT','ELECT','ELITE','ELOPE','ELUDE','EMAIL','EMOTE','EMPOWER','EMPTY','ENACT',
  'ENDOW','ENJOY','ENTER','ENVOY','EPOCH','ERODE','ERRANT','ETHOS','EVADE','EVERY',
  'EXACT','EXERT','EXILE','EXIST','EXPEL','EXTRA',
  // F
  'FLAME','FORGE','FLAIR','FUDGE','FRISK','FERRY','FABLE','FACED','FACET','FAITH',
  'FALSE','FANCY','FARCE','FATAL','FAULT','FEAST','FENCE','FERAL','FETAL','FETID',
  'FEVER','FEWER','FIEND','FIFTH','FIFTY','FINCH','FIRST','FISHY','FITLY','FIXED',
  'FJORD','FLAIL','FLAKE','FLAKY','FLANK','FLARE','FLASH','FLASK','FLECK','FLEET',
  'FLESH','FLICK','FLINCH','FLINT','FLIT','FLOCK','FLOOD','FLOOR','FLOSS','FLOUT',
  'FLOWN','FLUFF','FLUNK','FLUTE','FOAMY','FOCAL','FOGGY','FOLIO','FOLLY','FORAY',
  'FORCE','FORTE','FORUM','FOUND','FRAIL','FRAME','FRANK','FRAUD','FREAK','FREED',
  'FRESH','FRIAR','FROTH','FROZE','FRUGAL','FULLY','FUNGI','FUNKY','FUNNY','FUZZY',
  // G
  'GRACE','GLOBE','GROWL','GUISE','GUSTO','GULLY','GAUDY','GAUZE','GAVEL','GAWKY',
  'GEEKY','GIRTH','GIVEN','GIZMO','GLAND','GLARE','GLEAM','GLEAN','GLINT','GLOOM',
  'GLOSS','GLOVE','GLYPH','GNASH','GNOME','GOING','GOLEM','GORGE','GOUGE','GRACE',
  'GRADE','GRAFT','GRAIL','GRAMP','GRASP','GRASS','GRATE','GRAVY','GRAZE','GREED',
  'GREET','GRIME','GRIMY','GRIPE','GROAN','GROIN','GROOM','GROPE','GROSS','GROUT',
  'GROVE','GRUEL','GRUFF','GRUMP','GUILE','GUISE','GULCH','GULLY','GUSTO','GUSHY',
  // H
  'HEART','HASTE','HUMOR','HYENA','HAIKU','HAIRY','HANDY','HARPY','HARSH','HATCH',
  'HAUNT','HAVEN','HAVOC','HEADY','HEAVY','HEDGE','HEIST','HENCE','HERBY','HERON',
  'HINGE','HIPPO','HOARD','HOARY','HOBBY','HOLLY','HOMER','HONEY','HONOR','HORDE',
  'HORNS','HORSE','HOTEL','HOVEL','HOVER','HUMAN','HUMID','HUMPH','HUNCH','HUSKY',
  'HYPER',
  // I
  'IRATE','INTER','INFER','IRONY','ICING','IDEAL','IDIOM','IDIOT','IDYLL','IMAGE',
  'IMBUE','IMPEL','INANE','INCUR','INDEX','INDIE','INEPT','INERT','INLAY','INNER',
  'INPUT','INTER','INTRO','IONIC','IRATE','IVORY',
  // J
  'JEWEL','JOUST','JAUNT','JUMPY','JOKER','JAZZY','JELLY','JINGO','JOUST','JUDGE',
  'JUMBO','JUICY','KINKY','JUROR',
  // K
  'KNEEL','KNACK','KNAVE','KAYAK','KOALA','KARMA','KEBAB','KIOSK','KNEAD','KNIFE',
  'KNOCK','KNOWN','KUDOS',
  // L
  'LEMON','LODGE','LYRIC','LAPEL','LEAPT','LABEL','LANCE','LANKY','LAPEL','LAPSE',
  'LASER','LATCH','LATER','LATHE','LATTE','LAUGH','LAYER','LEACH','LEAFY','LEARN',
  'LEASE','LEASH','LEAVE','LEDGE','LEGER','LEGAL','LEKAN','LEVEL','LIBEL','LIGHT',
  'LINER','LINGO','LITHE','LOCAL','LODGE','LOOPY','LORRY','LOUSY','LOVER','LOWLY',
  'LUCID','LUCKY','LUCRE','LUMPY','LUNAR','LUSTY','LYING',
  // M
  'MAPLE','MOOSE','MICRO','MIRTH','MOCHA','MANGY','MANIC','MARCH','MARRY','MARSH',
  'MATTE','MEALY','MEATY','MEDIA','MELEE','MERCY','METAL','METER','MIGHT','MINCE',
  'MISER','MISTY','MOIST','MOLDY','MONTH','MOODY','MORAL','MOSSY','MOTTO','MOUNT',
  'MOURN','MUCKY','MUDDY','MULCH','MULLS','MUMMY','MURKY','MUSTY','MYRRH','NAIVE',
  // N
  'NIGHT','NOBLE','NYMPH','NAVAL','NEEDY','NERVE','NEWLY','NICER','NIFTY','NIFTY',
  'NIMBLE','NIPPY','NITTY','NOBLY','NOISY','NOMAD','NONCE','NUTTY',
  // O
  'OCEAN','ORBIT','OPTIC','OXIDE','OPERA','ONSET','OAKUM','OBESE','OCCUR','OLIVE',
  'ONSET','OPAQUE','OUNCE','OUTDO','OVARY','OVOID','OWNED',
  // P
  'PLANE','PILOT','PRISM','PERKY','PIVOT','PROBE','PADDY','PAINT','PANSY','PASTE',
  'PATCH','PATSY','PAUSE','PEACE','PEACH','PEARL','PEEVE','PENAL','PENNY','PERCH',
  'PERIL','PERKY','PETAL','PETTY','PHASE','PHONY','PIANO','PIECE','PIXEL','PIXIE',
  'PLAID','PLAIN','PLANK','PLANT','PLASH','PLATE','PLAZA','PLEAD','PLEAT','PLUCK',
  'PLUMB','PLUME','PLUMP','PLUNK','PLUSH','POACH','POACH','PODGY','POLAR','POLKA',
  'POLYP','POOCH','POUTY','POWER','PRANK','PRAWN','PRESS','PRIDE','PRIMP','PRIOR',
  'PRIVY','PRIZE','PRONE','PRONG','PROOF','PROSE','PROUD','PROVE','PROWL','PRUDE',
  'PRUNE','PUDGY','PULSE','PUNCH','PUPIL','PUPPY','PURGE','PUSHY','PYGMY',
  // Q
  'QUEEN','QUILT','QUOTA','QUALM','QUACK','QUAFF','QUAKE','QUALM','QUERY','QUEUE',
  'QUICK','QUIET','QUIRK','QUIVER',
  // R
  'RIVER','REIGN','RAVEN','RISKY','RADAR','RALLY','RAMEN','RAMP','RAPID','RASPY',
  'RATTY','REBEL','REEDY','REFIT','REGAL','RELAX','REMIT','REPAY','REPEL','RERUN',
  'RESIN','REVEL','RIDGE','RIFLE','RIGID','RIPEN','RISEN','RIVET','ROAST','ROBOT',
  'ROCKY','RODEO','ROUGE','ROUGH','ROWDY','ROYAL','RUMOR','RURAL','RUSTY',
  // S
  'STONE','SWAMP','SHAWL','SCALD','STOMP','SHUNT','SMEAR','GLARE','SMART','SABLE',
  'SADLY','SAINT','SALTY','SALVE','SANDY','SASSY','SAUCE','SAVOR','SCALD','SCALP',
  'SCALY','SCAMP','SCARE','SCARF','SCARY','SCENE','SCONE','SCOOP','SCOPE','SCOUR',
  'SCOUT','SCREW','SCRUB','SEEDY','SEIZE','SERVE','SETUP','SEVEN','SHACK','SHADE',
  'SHADY','SHAFT','SHAKY','SHAME','SHAPE','SHARE','SHARK','SHARP','SHEEN','SHEER',
  'SHELL','SHIFT','SHINE','SHINY','SHIRT','SHOCK','SHORE','SHOUT','SHOVE','SHOWN',
  'SHRUG','SIEGE','SIGHT','SILKY','SILLY','SINCE','SIXTH','SIXTY','SIZED','SKILL',
  'SKIMP','SKUNK','SLAIN','SLANG','SLANT','SLASH','SLICK','SLIDE','SLIME','SLING',
  'SLINK','SLOPE','SLOTH','SLUMP','SLUNK','SLURP','SMALL','SMASH','SMELL','SMILE',
  'SMITE','SMOKE','SNAIL','SNAKE','SNARE','SNEAK','SNIFF','SNORE','SNORT','SOLAR',
  'SOLID','SOLVE','SORRY','SOUTH','SPARK','SPAWN','SPEAK','SPEAR','SPECK','SPEND',
  'SPICE','SPILL','SPINE','SPITE','SPLIT','SPOKE','SPOOK','SPOON','SPORE','SPOUT',
  'SPREE','SPRIG','SPUNK','SQUAD','SQUAT','SQUID','STAIN','STALE','STALL','STAMP',
  'STAND','STANK','STARK','START','STASH','STAVE','STEAK','STEAL','STEAM','STEEL',
  'STEEP','STEER','STERN','STICK','STIFF','STILL','STING','STOCK','STOIC','STOKE',
  'STONY','STOOD','STORE','STARK','STORM','STORY','STOUT','STOVE','STRAP','STRAW',
  'STRAY','STRIP','STRUT','STUCK','STUDY','STUMP','STUNG','STUNK','STUNT','STYLE',
  'SUGAR','SUITE','SULKY','SUNNY','SURGE','SWEAR','SWEAT','SWEEP','SWEET','SWIFT',
  'SWIPE','SWIRL','SWOOP',
  // T
  'TIGER','THORN','TWIRL','TAFFY','TABOO','TROUT','TRIPE','TAKEN','TALLY','TALON',
  'TAUNT','TAWNY','TAUNT','TENSE','TEPID','THANK','THANE','THEME','THERE','THICK',
  'TIDAL','TIGER','TIGHT','TILTED','TINGE','TIPSY','TITHE','TITLE','TOAST','TONIC',
  'TOPAZ','TORSO','TOTAL','TOUCH','TOUGH','TOWEL','TOXIC','TRACK','TRADE','TRAIL',
  'TRAIN','TRAMP','TRASH','TREAT','TREND','TRIAL','TRICK','TRIED','TROUT','TROVE',
  'TRUCE','TRULY','TRUMP','TRUNK','TRUSS','TRUST','TRUTH','TUBER','TUMMY','TUNER',
  'TUNIC','TURBO','TUTOR','TWANG','TWICE','TWILL','TWINGE','TWIST','TYING',
  // U
  'ULTRA','UPSET','USURP','ULCER','UNFIT','UNDUE','UNKEMPT','UNTIE','UNWED','UPPER',
  'URBAN','USAGE','USEFUL',
  // V
  'VIVID','VAULT','VOUCH','VICAR','VISOR','VAPID','VALOR','VALVE','VENOM','VERSE',
  'VIBES','VIGIL','VIOLA','VIRAL','VISIT','VISOR','VITAL','VIVID','VOTER','VOUCH',
  // W
  'WHEAT','WRATH','WOVEN','WINDY','WORDY','WAFER','WALTZ','WARTY','WEARY','WEDGE',
  'WEEDY','WEIRD','WHACK','WHALE','WHIFF','WHILE','WHIRL','WHISK','WITTY','WOODY',
  'WOOZY','WORST','WRATH','WREAK','WRECK','WRING','WRONG',
  // X Y Z
  'XENON','YACHT','YEARN','YEAST','YIELD','ZEBRA','ZESTY','ZONAL','ZOMBI',
]

// Only keep exactly 5-letter plain-latin words (safety filter) — built-in fallback pool
const BUILTIN_FR = [...new Set(WORDS_FR.filter(w => /^[A-Z]{5}$/.test(w)))]
const BUILTIN_EN = [...new Set(WORDS_EN.filter(w => /^[A-Z]{5}$/.test(w)))]

// Runtime answer pool — starts with built-ins, gets replaced after external list loads
const answerPool = { fr: BUILTIN_FR, en: BUILTIN_EN }
// Full validation set (built-ins + external) for fast local lookup
const validationSet = { fr: new Set(BUILTIN_FR), en: new Set(BUILTIN_EN) }

/**
 * Call this once on app start (or when language loads).
 * Merges the externally fetched word list into the runtime pools.
 */
export function injectWordList(lang, words) {
  if (!words || words.length === 0) return
  // Replace answer pool with the larger external list
  answerPool[lang] = words
  // Merge into validation set
  words.forEach(w => validationSet[lang].add(w))
}

export function getRandomWord(lang) {
  const list = answerPool[lang] ?? BUILTIN_EN
  return list[Math.floor(Math.random() * list.length)]
}

export function getWordCount(lang) {
  return answerPool[lang]?.length ?? 0
}

// Cache validated words so we don't hit the API twice for the same word
const validationCache = {}

/**
 * Validate a guess:
 * 1. Check local validation set (instant, covers built-in + fetched list)
 * 2. Fall back to Free Dictionary API for anything not in local set
 * Returns: 'valid' | 'invalid' | 'offline'
 */
export async function isValidWord(word, lang) {
  const upper = word.toUpperCase()
  const key = `${lang}:${upper}`
  if (key in validationCache) return validationCache[key]

  // Fast local check — covers fetched list too
  if (validationSet[lang].has(upper)) {
    validationCache[key] = 'valid'
    return 'valid'
  }

  // API language codes: 'en' maps to 'en_US', 'fr' maps to 'fr'
  const apiLang = lang === 'fr' ? 'fr' : 'en_US'
  const url = `https://api.dictionaryapi.dev/api/v2/entries/${apiLang}/${word.toLowerCase()}`

  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(3000) })
    const result = res.ok ? 'valid' : 'invalid'
    validationCache[key] = result
    return result
  } catch {
    // Network error / offline — fall back: reject unknown words
    validationCache[key] = 'offline'
    return 'offline'
  }
}
